#!/usr/bin/env python3
import os
from lib.EntrypointScriptBuilder import EntrypointScriptBuilder


def main():
    builder = EntrypointScriptBuilder(os.environ)
    script_source = builder.build()
    f = open('/tmp/run', 'w')
    f.write(script_source)
    f.flush()
    f.close

if __name__ == '__main__':
    main()
